name: Actualizar Lista M3U Disney

on:
  schedule:
    # Se ejecuta automáticamente todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite que también puedas activarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar librerías
      run: pip install requests

    - name: Ejecutar el extractor
      env:
        # Usa el token del sistema de forma segura para tener permisos de escritura
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: python extractor.py
