name: Actualizar Token Cada 6 Horas

on:
  schedule:
    - cron: '1 */6 * * *'
  workflow_dispatch: # ESTA LÍNEA ES OBLIGATORIA PARA QUE APAREZCA EL BOTÓN MANUAL

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4.2.2

    - name: Configurar Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Ejecutar script de extracción
      run: python script.py

    - name: Guardar cambios en el repositorio
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add token.txt
        git commit -m "Automatización: Token actualizado" || echo "Sin cambios detectados"
        git push origin HEAD:${{ github.ref }}
